version: '3.4'

services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw

  siberstetstask.server:
    image: ${DOCKER_REGISTRY-}siberstetstaskserver
    build:
      context: .
      dockerfile: SibersTetsTask.Server/Dockerfile
