version: '3.4'

services:
  stroitrendtesttask.server:
    image: ${DOCKER_REGISTRY-}stroitrendtesttaskserver
    build:
      context: .
      dockerfile: StroiTrendTestTask.Server/Dockerfile
  client:
         image: ${DOCKER_REGISTRY-}stroitrendtesttaskclint
         build:
           context: ./stroitrendtesttask.client
           dockerfile: Dockerfile
         ports:
               -  "80:80" 
         container_name: client